---
title: Introducing the `interactr` package
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Introducing the `interactr` package}
  %\VignetteEngine{knitr::rmarkdown}
---

This originally stemmed from an honours project.

## About:
The `interactr` package was built to try solve a simple problem:
achieve on-plot interactivity and create simplistic web interactive visuals
on plots originally drawn or generated in R. That is, try turn your static
R plot into an interactive one!

After investigating many existing tools for creating interactive data visuals,
many of these were restricted to certain interactions.
Many are still being developed as we speak
(such as plotly, rbokeh and highcharter, and ggvis).
There is a trade off between how we can customise on-plot interactivity with
lower level tools that required a knowledge of HTML/CSS/JavaScript, and higher
level tools that produced standardised plots but are not entirely extensible
to the user.

`interactr` is mainly built upon DOM, gridSVG and the grid graphics system in R.
With gridSVG, we are able to produce SVG plots from R, but also be able
to easily traverse between data and SVG elements easily, while DOM allows
the user to call and manipulate parts of the Document Object Model from R.
We've aimed to make an interface where the user doesn't need to worry
about web technologies, but focus on what kind of visuals and interactions
they want to achieve from the data they've got.

## The process

The idea is based upon 5 simple steps:
- Draw plot or elements in R
- Identify elements to interact with
- Determine what kind of interaction is to be achieved
- Attach and link interactions and events to targeted elements
- Send interaction instructions and plot to the browser

**THIS PACKAGE IS ENTIRELY DEVELOPMENTAL AND IS NOT STABLE. USE AT YOUR OWN RISK.
 It is only a proof of concept. It is a work in progress.**

For examples, visit the additionals section.

## The TLDR section for the curious:

**Why not use/build off shiny?**
There are a lot of similarities between shiny and the DOM package, in which both
have a way of communicating between R and the browser. shiny is very popular
and has both the power to be extensible and flexible to the user. However,
one of the disadvantages of it is that on-plot interactivity is limited. Whenever
a user changes an input, either plots must be entirely redrawn which leads to
unnecessary computation and makes things inefficient. It is possible to be
able to modify plots through shiny, but this requires the user to know
JavaScript (+ the plot must be either an SVG or a canvas element within
an SVG). A previous idea was to be able to generate javascript code within
to allow users to 'insert' into their shiny app, but does not provide a
cohesive and generic solution. Instead, we chose to use the DOM package
simply because some of these things can be done within R and takes care
of this problem.

**Comparison to using standard JavaScript**
Because requests are being sent back and forth between R and the browser,
the cost of this is the time taken for the 'interaction' to be displayed.
As we see from the example above with highlighting points on a scatter plot,
it takes a while for this to occur before all points are highlighted. I
n comparison, when we use standard JavaScript it is much faster because
there is no need to fetch requests from R. However, the solution in JavaScript
is only applicable for plots where both the box plot and the points are in
the same viewport.


...and more stuff coming soon.
